DROP DATABASE IF EXISTS `students_db`;

CREATE DATABASE `students_db`;

USE `students_db`;

CREATE TABLE students (
	student_name VARCHAR(100),
    roll_no VARCHAR(10),
    class_level INT,
    class_section VARCHAR(1),
    percentage VARCHAR(10),
    result_grade VARCHAR(100)
);

INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A001', 9, 'C', '52.67%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2027G1A002', 9, 'C', '30.18%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2027G1A003', 9, 'C', '79.85%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2027G1A004', 10, 'B', '52.49%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2026G1A005', 9, 'A', '54.39%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A006', 10, 'B', '57.2%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2027G1A007', 8, 'C', '57.85%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2027G1A008', 8, 'B', '61.24%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2026G1A009', 8, 'A', '73.82%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2025G1A010', 8, 'A', '23.7%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2027G1A011', 8, 'B', '53.16%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2025G1A012', 10, 'C', '50.72%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2025G1A013', 8, 'C', '75.01%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A014', 8, 'A', '84.33%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A015', 8, 'C', '39.94%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A016', 8, 'B', '73.41%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2027G1A017', 9, 'B', '69.01%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A018', 10, 'B', '91.78%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A019', 9, 'A', '87.19%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A020', 9, 'C', '39.14%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A021', 10, 'B', '38.76%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2026G1A022', 10, 'A', '31.07%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2026G1A023', 10, 'A', '76.51%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A024', 9, 'B', '63.41%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2025G1A025', 8, 'B', '51.16%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A026', 8, 'C', '50.43%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2026G1A027', 9, 'B', '88.28%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2027G1A028', 10, 'C', '63.69%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2025G1A029', 9, 'A', '41.83%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A030', 9, 'B', '73.51%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2027G1A031', 8, 'B', '93.56%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A032', 8, 'B', '67.35%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2025G1A033', 10, 'B', '30.86%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A034', 8, 'B', '50.33%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2026G1A035', 9, 'B', '80.9%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2026G1A036', 9, 'B', '86.79%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A037', 10, 'C', '24.17%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2025G1A038', 10, 'A', '82.5%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2025G1A039', 8, 'A', '87.14%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2025G1A040', 8, 'A', '57.88%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2027G1A041', 8, 'B', '75.96%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2025G1A042', 10, 'C', '97.1%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2025G1A043', 9, 'A', '66.29%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A044', 10, 'B', '51.73%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2025G1A045', 10, 'C', '86.45%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2025G1A046', 10, 'B', '88.02%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2025G1A047', 10, 'A', '47.78%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2027G1A048', 9, 'A', '60.48%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2025G1A049', 9, 'B', '28.44%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2027G1A050', 9, 'C', '32.24%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2027G1A051', 10, 'C', '41.61%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A052', 9, 'B', '86.06%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2026G1A053', 9, 'A', '86.46%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A054', 9, 'A', '80.04%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A055', 10, 'B', '46.91%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A056', 8, 'B', '36.97%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2026G1A057', 9, 'C', '76.09%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A058', 8, 'C', '95.85%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2025G1A059', 10, 'B', '59.09%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A060', 9, 'C', '76.95%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A061', 8, 'B', '37.73%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2026G1A062', 10, 'C', '49.52%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2027G1A063', 9, 'B', '99.73%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A064', 9, 'C', '56.3%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2026G1A065', 8, 'A', '77.7%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2025G1A066', 10, 'C', '96.07%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A067', 8, 'C', '58.74%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A068', 10, 'B', '98.44%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2026G1A069', 8, 'B', '34.36%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2027G1A070', 10, 'A', '41.94%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2027G1A071', 9, 'C', '95.53%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A072', 8, 'C', '42.75%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A073', 9, 'A', '97.24%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2026G1A074', 8, 'A', '52.06%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2027G1A075', 10, 'C', '24.29%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2027G1A076', 9, 'A', '99.51%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2027G1A077', 9, 'C', '67.69%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2025G1A078', 10, 'B', '56.04%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A079', 10, 'B', '44.43%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2025G1A080', 10, 'C', '27.94%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A081', 8, 'B', '72.83%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A082', 8, 'C', '26.01%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2026G1A083', 9, 'C', '67.5%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2025G1A084', 8, 'B', '76.56%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A085', 10, 'A', '93.91%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A086', 8, 'B', '29.18%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A087', 8, 'B', '86.13%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2025G1A088', 8, 'B', '67.6%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2026G1A089', 9, 'A', '57.5%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A090', 9, 'B', '60.04%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A091', 8, 'C', '23.19%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2027G1A092', 9, 'C', '40.03%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2025G1A093', 10, 'C', '66.97%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2027G1A094', 9, 'C', '23.22%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2026G1A095', 10, 'C', '55.38%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2025G1A096', 10, 'B', '70.78%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A097', 9, 'B', '52.67%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2027G1A098', 8, 'A', '46.38%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A099', 10, 'B', '85.09%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2025G1A100', 9, 'A', '45.16%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2025G1A101', 9, 'C', '85.99%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2027G1A102', 10, 'B', '53.06%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A103', 9, 'C', '80.52%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A104', 8, 'B', '63.94%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2026G1A105', 10, 'B', '29.71%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2025G1A106', 10, 'A', '44.86%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2027G1A107', 9, 'A', '37.98%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A108', 8, 'C', '86.57%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2027G1A109', 9, 'C', '76.43%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2026G1A110', 9, 'A', '56.54%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2026G1A111', 8, 'C', '60.66%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A112', 9, 'B', '47.19%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A113', 8, 'B', '78.08%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A114', 10, 'B', '89.22%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2027G1A115', 9, 'B', '46.6%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A116', 9, 'B', '89.57%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A117', 9, 'A', '88.48%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2025G1A118', 9, 'C', '57.84%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2026G1A119', 10, 'C', '98.47%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A120', 8, 'C', '97.23%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2025G1A121', 9, 'A', '62.08%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A122', 10, 'A', '52.8%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A123', 9, 'B', '47.08%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2027G1A124', 8, 'B', '88.19%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A125', 9, 'C', '77.5%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2027G1A126', 8, 'C', '25.47%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2025G1A127', 10, 'A', '54.72%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2027G1A128', 10, 'A', '55.49%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2025G1A129', 8, 'B', '83.69%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2026G1A130', 9, 'B', '31.65%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A131', 10, 'C', '83.4%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A132', 8, 'C', '89.67%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A133', 8, 'B', '93.03%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A134', 9, 'C', '40.32%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A135', 8, 'B', '92.1%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2025G1A136', 8, 'B', '95.62%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2026G1A137', 10, 'B', '75.23%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A138', 8, 'B', '88.27%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2025G1A139', 9, 'C', '48.72%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A140', 9, 'A', '98.24%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2026G1A141', 8, 'C', '89.21%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2027G1A142', 10, 'B', '86.63%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2025G1A143', 10, 'B', '37.52%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A144', 9, 'C', '80.45%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2027G1A145', 8, 'C', '71.71%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2026G1A146', 8, 'C', '49.19%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A147', 9, 'B', '79.8%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A148', 8, 'C', '90.12%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2027G1A149', 10, 'B', '86.44%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2026G1A150', 9, 'C', '89.63%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A151', 8, 'A', '80.33%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A152', 10, 'C', '98.4%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A153', 8, 'B', '21.11%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2025G1A154', 9, 'B', '73.83%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A155', 9, 'C', '95.22%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2027G1A156', 8, 'B', '22.0%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A157', 10, 'A', '71.81%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2027G1A158', 9, 'C', '52.66%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A159', 8, 'B', '99.67%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2025G1A160', 8, 'C', '30.85%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A161', 10, 'C', '75.72%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2026G1A162', 10, 'C', '78.13%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2027G1A163', 8, 'B', '69.25%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2025G1A164', 10, 'B', '37.38%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2025G1A165', 9, 'A', '98.47%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2027G1A166', 10, 'B', '24.84%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2025G1A167', 8, 'B', '27.33%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A168', 10, 'C', '97.69%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2026G1A169', 8, 'A', '82.96%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2025G1A170', 10, 'A', '66.91%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2026G1A171', 8, 'C', '20.23%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2025G1A172', 10, 'B', '83.88%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2027G1A173', 8, 'A', '21.19%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2027G1A174', 9, 'A', '33.94%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2025G1A175', 10, 'B', '62.09%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A176', 9, 'B', '61.06%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A177', 10, 'A', '95.63%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2027G1A178', 10, 'C', '44.13%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ashwin', '2025G1A179', 9, 'B', '54.1%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A180', 10, 'B', '25.88%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A181', 10, 'A', '25.25%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A182', 10, 'C', '63.87%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2026G1A183', 10, 'C', '43.59%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2027G1A184', 9, 'A', '83.45%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2027G1A185', 10, 'C', '77.67%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Deepa', '2026G1A186', 9, 'A', '53.11%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Harish', '2026G1A187', 9, 'C', '27.61%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Geeta', '2026G1A188', 10, 'B', '49.94%', 'Third class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Chandan', '2027G1A189', 9, 'A', '27.3%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2025G1A190', 9, 'A', '79.57%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2025G1A191', 10, 'A', '66.92%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2027G1A192', 9, 'C', '29.78%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Feroz', '2027G1A193', 9, 'C', '24.12%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A194', 9, 'B', '28.29%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Isha', '2025G1A195', 8, 'C', '58.58%', 'Second class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Bharath', '2026G1A196', 10, 'B', '29.19%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A197', 8, 'B', '87.61%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A198', 10, 'C', '64.54%', 'First class_level');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Jayanth', '2027G1A199', 10, 'B', '22.32%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Esha', '2027G1A200', 9, 'B', '48.08%', 'Third class_level');