DROP DATABASE IF EXISTS `students_db`;

CREATE DATABASE `students_db`;

USE `students_db`;

CREATE TABLE students (
	student_name VARCHAR(100),
    roll_no VARCHAR(10),
    class_level INT,
    class_section VARCHAR(1),
    percentage VARCHAR(10),
    result_grade VARCHAR(100)
);

INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sai Patel', '2027G1A001', 8, 'A', '72.7%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ira Sharma', '2027G1A002', 9, 'D', '72.34%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nitya Verma', '2027G1A003', 10, 'C', '87.75%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kunal Das', '2027G1A004', 10, 'D', '23.66%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Reyansh Reddy', '2027G1A005', 9, 'D', '61.48%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nitya Ghosh', '2027G1A006', 9, 'A', '99.83%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanvi Gupta', '2027G1A007', 10, 'C', '50.62%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sai Gupta', '2027G1A008', 8, 'B', '99.3%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ira Chopra', '2027G1A009', 10, 'C', '35.41%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vivaan Malhotra', '2027G1A010', 9, 'D', '64.72%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Riya Joshi', '2027G1A011', 8, 'D', '72.39%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vanya Singh', '2027G1A012', 8, 'A', '20.43%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kashvi Kapoor', '2027G1A013', 8, 'C', '21.72%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Shiv Agarwal', '2027G1A014', 10, 'A', '20.23%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Pooja Patel', '2027G1A015', 9, 'C', '25.65%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kashvi Rastogi', '2027G1A016', 9, 'C', '35.77%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arjun Das', '2027G1A017', 9, 'C', '45.36%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Pooja Bansal', '2027G1A018', 8, 'A', '82.18%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Meera Jain', '2027G1A019', 10, 'D', '32.81%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Mira Rastogi', '2027G1A020', 9, 'C', '77.71%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nitya Singh', '2027G1A021', 8, 'D', '62.09%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ayaan Jain', '2027G1A022', 9, 'B', '82.97%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kritika Kumar', '2027G1A023', 9, 'B', '62.6%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Myra Joshi', '2027G1A024', 9, 'C', '61.26%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Shiv Kumar', '2027G1A025', 10, 'A', '51.77%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kartik Ghosh', '2027G1A026', 10, 'C', '25.9%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ira Kumar', '2027G1A027', 9, 'D', '81.05%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Meera Bansal', '2027G1A028', 9, 'B', '62.93%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aarav Kumar', '2027G1A029', 9, 'D', '80.9%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ishita Nair', '2027G1A030', 9, 'C', '42.37%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Riya Jain', '2027G1A031', 9, 'A', '80.79%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rohan Gupta', '2027G1A032', 9, 'C', '58.47%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aadhya Malhotra', '2027G1A033', 9, 'A', '76.9%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Charvi Ghosh', '2027G1A034', 8, 'C', '78.67%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aditya Nair', '2027G1A035', 10, 'D', '86.48%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Krishna Sharma', '2027G1A036', 10, 'B', '76.93%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Meera Singh', '2027G1A037', 10, 'B', '88.47%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rohan Kapoor', '2027G1A038', 10, 'C', '86.0%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Natasha Joshi', '2027G1A039', 8, 'D', '22.01%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arjun Mehta', '2027G1A040', 9, 'D', '65.89%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ishita Gupta', '2027G1A041', 8, 'D', '98.7%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Charvi Trivedi', '2027G1A042', 8, 'C', '88.39%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Neel Nair', '2027G1A043', 8, 'B', '80.07%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kunal Kumar', '2027G1A044', 9, 'D', '20.29%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nisha Sharma', '2027G1A045', 8, 'B', '97.04%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aadhya Rastogi', '2027G1A046', 10, 'C', '32.14%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanya Kumar', '2027G1A047', 9, 'B', '44.22%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Navya Kumar', '2027G1A048', 9, 'A', '64.91%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kashvi Gupta', '2027G1A049', 8, 'C', '54.81%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Navya Das', '2027G1A050', 9, 'B', '74.42%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Siya Bansal', '2027G1A051', 10, 'C', '20.35%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ishaan Jain', '2027G1A052', 10, 'D', '39.61%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Navya Kumar', '2027G1A053', 9, 'A', '65.87%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Krishna Nair', '2027G1A054', 9, 'C', '74.45%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ishita Rastogi', '2027G1A055', 10, 'A', '23.27%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kunal Das', '2027G1A056', 10, 'D', '35.93%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vanya Singh', '2027G1A057', 9, 'B', '67.94%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Anaya Nair', '2027G1A058', 9, 'C', '63.6%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Shiv Verma', '2027G1A059', 10, 'A', '20.71%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Navya Malhotra', '2027G1A060', 9, 'B', '74.72%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Shiv Kapoor', '2027G1A061', 8, 'B', '44.16%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aadhya Trivedi', '2027G1A062', 10, 'A', '86.49%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nitya Gupta', '2027G1A063', 10, 'D', '21.42%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arnav Malhotra', '2027G1A064', 9, 'C', '87.93%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nitya Das', '2027G1A065', 10, 'C', '74.57%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vivaan Verma', '2027G1A066', 10, 'A', '25.61%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Pooja Nair', '2027G1A067', 9, 'B', '99.61%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ishaan Trivedi', '2027G1A068', 8, 'D', '66.47%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aditya Gupta', '2027G1A069', 8, 'A', '74.64%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kartik Singh', '2027G1A070', 9, 'C', '92.84%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Anaya Kumar', '2027G1A071', 10, 'D', '41.42%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rohan Gupta', '2027G1A072', 8, 'D', '70.92%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aditya Sharma', '2027G1A073', 9, 'B', '78.63%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Reyansh Kumar', '2027G1A074', 8, 'C', '53.96%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Mira Reddy', '2027G1A075', 8, 'D', '46.54%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Priya Nair', '2027G1A076', 10, 'C', '33.55%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sai Nair', '2027G1A077', 8, 'B', '37.27%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Pooja Das', '2027G1A078', 8, 'C', '99.82%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Meera Kumar', '2027G1A079', 8, 'A', '84.93%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Reyansh Das', '2027G1A080', 10, 'B', '34.22%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Charvi Joshi', '2027G1A081', 10, 'B', '86.64%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kritika Kumar', '2027G1A082', 8, 'C', '47.5%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Meera Chopra', '2027G1A083', 9, 'C', '68.35%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Diya Singh', '2027G1A084', 9, 'C', '93.19%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Navya Verma', '2027G1A085', 10, 'A', '57.68%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Natasha Ghosh', '2027G1A086', 9, 'A', '88.68%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Mira Jain', '2027G1A087', 10, 'A', '53.64%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sara Reddy', '2027G1A088', 10, 'C', '72.52%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kunal Das', '2027G1A089', 8, 'A', '58.42%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kabir Malhotra', '2027G1A090', 10, 'C', '62.66%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vivaan Chopra', '2027G1A091', 8, 'B', '98.98%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kartik Das', '2027G1A092', 8, 'D', '49.99%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kartik Gupta', '2027G1A093', 8, 'A', '64.85%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kunal Kapoor', '2027G1A094', 10, 'B', '23.36%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanvi Ghosh', '2027G1A095', 9, 'A', '75.06%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanya Rastogi', '2027G1A096', 10, 'D', '28.09%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sai Chopra', '2027G1A097', 10, 'D', '86.11%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arjun Gupta', '2027G1A098', 10, 'D', '78.58%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanya Singh', '2027G1A099', 9, 'C', '95.29%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aarav Ghosh', '2027G1A100', 9, 'C', '55.05%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Neel Agarwal', '2027G1A101', 10, 'A', '67.67%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vanya Bansal', '2027G1A102', 8, 'B', '30.73%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanvi Trivedi', '2027G1A103', 8, 'D', '80.1%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Anika Gupta', '2027G1A104', 10, 'A', '43.4%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Natasha Nair', '2027G1A105', 8, 'D', '26.53%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Priya Joshi', '2027G1A106', 8, 'D', '75.19%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sara Ghosh', '2027G1A107', 8, 'C', '45.5%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nisha Kumar', '2027G1A108', 8, 'C', '83.97%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Natasha Agarwal', '2027G1A109', 8, 'B', '34.24%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Shiv Trivedi', '2027G1A110', 8, 'B', '42.36%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aarav Das', '2027G1A111', 9, 'C', '40.36%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aarav Verma', '2027G1A112', 10, 'B', '69.52%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vivaan Kapoor', '2027G1A113', 8, 'B', '97.63%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kritika Patel', '2027G1A114', 10, 'A', '27.78%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kabir Bansal', '2027G1A115', 8, 'D', '69.07%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sai Mehta', '2027G1A116', 10, 'A', '48.56%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Yash Ghosh', '2027G1A117', 10, 'C', '75.59%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Charvi Agarwal', '2027G1A118', 9, 'B', '23.51%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aadhya Rastogi', '2027G1A119', 8, 'A', '42.99%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ishaan Das', '2027G1A120', 9, 'D', '30.27%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sara Malhotra', '2027G1A121', 8, 'A', '58.11%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanvi Das', '2027G1A122', 9, 'D', '56.61%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aadhya Trivedi', '2027G1A123', 8, 'B', '88.07%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Riya Nair', '2027G1A124', 10, 'B', '69.7%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Meera Mehta', '2027G1A125', 8, 'A', '94.17%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Lavanya Verma', '2027G1A126', 8, 'B', '41.09%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sara Bansal', '2027G1A127', 10, 'D', '78.49%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Mira Mehta', '2027G1A128', 9, 'D', '46.62%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tara Patel', '2027G1A129', 9, 'D', '31.16%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ira Bansal', '2027G1A130', 10, 'B', '79.79%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nitya Das', '2027G1A131', 10, 'C', '59.2%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nisha Kapoor', '2027G1A132', 8, 'B', '52.96%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vihaan Verma', '2027G1A133', 10, 'C', '73.21%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Mira Gupta', '2027G1A134', 8, 'A', '55.53%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arjun Rastogi', '2027G1A135', 10, 'D', '57.79%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arjun Rastogi', '2027G1A136', 8, 'C', '86.35%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Anaya Agarwal', '2027G1A137', 9, 'B', '49.88%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Priya Sharma', '2027G1A138', 8, 'D', '99.65%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Charvi Singh', '2027G1A139', 10, 'C', '42.7%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rudra Reddy', '2027G1A140', 10, 'D', '48.86%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sai Kapoor', '2027G1A141', 8, 'B', '58.45%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Priya Ghosh', '2027G1A142', 8, 'B', '96.08%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Riya Kapoor', '2027G1A143', 10, 'D', '31.97%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Saanvi Chopra', '2027G1A144', 8, 'D', '72.57%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanvi Verma', '2027G1A145', 10, 'B', '86.13%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kartik Sharma', '2027G1A146', 10, 'C', '51.69%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Avni Joshi', '2027G1A147', 8, 'A', '25.56%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Ayaan Singh', '2027G1A148', 10, 'B', '30.98%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tanvi Sharma', '2027G1A149', 10, 'D', '21.6%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tara Rastogi', '2027G1A150', 9, 'B', '51.59%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aditya Kumar', '2027G1A151', 8, 'A', '31.76%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kartik Kumar', '2027G1A152', 8, 'C', '37.11%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Avni Malhotra', '2027G1A153', 9, 'C', '64.3%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Siya Joshi', '2027G1A154', 9, 'C', '79.46%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arnav Ghosh', '2027G1A155', 10, 'C', '36.06%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Anaya Ghosh', '2027G1A156', 10, 'A', '45.24%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Saanvi Kumar', '2027G1A157', 10, 'C', '32.71%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Anaya Rastogi', '2027G1A158', 8, 'D', '30.36%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rudra Jain', '2027G1A159', 8, 'B', '66.37%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Avni Jain', '2027G1A160', 9, 'D', '57.62%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Diya Malhotra', '2027G1A161', 10, 'C', '91.0%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kunal Kumar', '2027G1A162', 10, 'C', '97.98%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kartik Kumar', '2027G1A163', 8, 'A', '28.43%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Lavanya Gupta', '2027G1A164', 8, 'D', '39.49%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Avni Kumar', '2027G1A165', 9, 'A', '88.46%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Charvi Agarwal', '2027G1A166', 8, 'C', '23.46%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Priya Patel', '2027G1A167', 8, 'B', '83.02%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Priya Agarwal', '2027G1A168', 10, 'D', '67.85%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vihaan Trivedi', '2027G1A169', 10, 'B', '23.19%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kunal Mehta', '2027G1A170', 8, 'B', '34.58%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tara Reddy', '2027G1A171', 10, 'A', '90.05%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kunal Chopra', '2027G1A172', 8, 'D', '77.07%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Avni Kapoor', '2027G1A173', 9, 'C', '69.7%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Reyansh Mehta', '2027G1A174', 9, 'B', '68.68%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arnav Reddy', '2027G1A175', 9, 'D', '44.83%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aadhya Bansal', '2027G1A176', 10, 'A', '96.23%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rohan Agarwal', '2027G1A177', 9, 'D', '79.93%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aarav Kumar', '2027G1A178', 9, 'A', '95.53%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Sai Sharma', '2027G1A179', 10, 'A', '27.72%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Neel Malhotra', '2027G1A180', 9, 'C', '50.73%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rohan Rastogi', '2027G1A181', 8, 'C', '32.75%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kabir Singh', '2027G1A182', 10, 'B', '28.53%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Avni Kapoor', '2027G1A183', 9, 'A', '85.8%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rohan Ghosh', '2027G1A184', 9, 'C', '57.42%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Shiv Rastogi', '2027G1A185', 8, 'D', '69.08%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Nitya Joshi', '2027G1A186', 9, 'D', '57.37%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Rudra Ghosh', '2027G1A187', 9, 'C', '27.54%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vivaan Nair', '2027G1A188', 9, 'C', '26.23%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aditya Mehta', '2027G1A189', 10, 'D', '28.92%', 'Failed');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kartik Agarwal', '2027G1A190', 10, 'C', '66.6%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tara Reddy', '2027G1A191', 8, 'D', '51.87%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Aarav Kumar', '2027G1A192', 10, 'D', '45.63%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Anika Trivedi', '2027G1A193', 9, 'A', '90.7%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Shiv Mehta', '2027G1A194', 10, 'C', '77.86%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Arnav Sharma', '2027G1A195', 9, 'A', '58.96%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Vihaan Gupta', '2027G1A196', 10, 'A', '46.34%', 'Pass');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Charvi Ghosh', '2027G1A197', 8, 'C', '68.02%', 'First Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Natasha Nair', '2027G1A198', 9, 'D', '89.15%', 'Distinction');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Tara Nair', '2027G1A199', 8, 'B', '50.41%', 'Second Class');
INSERT INTO students (student_name, roll_no, class_level, class_section, percentage, result_grade) VALUES ('Kashvi Ghosh', '2027G1A200', 8, 'D', '52.37%', 'Second Class');